language: ruby
before_install: gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - ruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
